import type { LocaleId } from "../../../../shared/contracts";

export const PIXEL_THEME_AGENT_GUIDE_URL = "https://github.com/teo-nex/CanvasTTY-design-for-agents/blob/main/AGENT_START.md";

export function pixelThemeAgentPrompt(locale: LocaleId): string {
  if (locale === "ru") {
    return `Создай для CanvasTTY новую пиксельную тему по приложенному референсу. Набор для агента: https://github.com/teo-nex/CanvasTTY-design-for-agents. Сначала изучи README, ${PIXEL_THEME_AGENT_GUIDE_URL} и SPEC.ru.md в этом репозитории. Актуальный импортёр и валидатор проверь в https://github.com/howdeploy/CanvasTTY. Референс задаёт художественное направление, но результат должен соответствовать техническому формату CanvasTTY. Сделай три уровня (minimal, detailed, master) и три отчётливо различимых состояния каждого (idle, working, completed), плюс отдельный background.png. Выдай установочный ZIP только с десятью финальными PNG и точными именами из инструкции; исходники и промежуточные файлы храни отдельно. Проверь ZIP реальным валидатором CanvasTTY, просмотри все девять кадров и фон, укажи отступы прозрачного проёма для каждого уровня. Не утверждай, что тема установлена в моём приложении, если ты её там не установил и не проверил. Референс прикрепляю к этому сообщению.`;
  }
  return `Create a new CanvasTTY pixel theme from the attached visual reference. Agent kit: https://github.com/teo-nex/CanvasTTY-design-for-agents. First read its README, ${PIXEL_THEME_AGENT_GUIDE_URL}, and SPEC.ru.md. Confirm the current importer and validator contract in https://github.com/howdeploy/CanvasTTY. The reference guides the art, but the output must satisfy CanvasTTY's technical format. Produce minimal, detailed, and master levels, each with visibly distinct idle, working, and completed states, plus a separate background.png. Deliver an install ZIP containing only the ten final PNGs with the exact filenames from the guide; keep sources and intermediate files separate. Validate the ZIP with CanvasTTY's validator, visually inspect all nine frames and the background, and report transparent-aperture insets for each level. Do not claim the theme is installed in my app unless you actually install and verify it. I am attaching the reference to this message.`;
}
